# -*- coding: utf-8 -*-
"""NLP - QLoRA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10A4DmErA59VK3HkWsLNlgXx9TLAI56rw

# **Group 19 - Baseline Vs. QLoRA Finetuning**
"""

!pip install transformers datasets peft trl bitsandbytes accelerate huggingface_hub -q

from huggingface_hub import login
login("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") # huggingface token

import torch
import pandas as pd
from datasets import Dataset
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import (
    LoraConfig,
    get_peft_model,
    prepare_model_for_kbit_training,
    PromptTuningConfig,
    TaskType,
)
from trl import SFTTrainer

"""## **Preprocessing**"""

df = pd.read_csv('/kaggle/input/datasets/suchintikasarkar/sentiment-analysis-for-mental-health/Combined Data.csv')
print(df.shape)
print(df.head())
print(df.columns)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

print(df['status'].value_counts())
print(f"\nTotal unique labels: {df['status'].nunique()}")
print(f"\nAny missing values: {df.isnull().sum()}")

"""## **Cleaning**"""

# Drop missing values
df = df.dropna(subset=['statement', 'status'])

# Drop the unnecessary index column
df = df.drop(columns=['Unnamed: 0'])

# Reset index
df = df.reset_index(drop=True)

print(f"Dataset size after cleaning: {df.shape}")
print(df.head())

import re
from bs4 import BeautifulSoup

def clean_text(text):
    # Remove HTML tags
    text = BeautifulSoup(str(text), "html.parser").get_text()
    # Remove URLs
    text = re.sub(r"http\S+|www\S+|https\S+", "", text, flags=re.MULTILINE)
    # Remove extra whitespace
    text = re.sub(r"\s+", " ", text).strip()
    return text

df['statement'] = df['statement'].apply(clean_text)

print("Cleaning done!")
print(df['statement'][0])

"""## **Converting the dataset to the instruction→target format**"""

def format_prompt(row):
    return f"""### Instruction: Classify the mental health status of the following statement.

### Statement: {row['statement']}

### Response: {row['status']}"""

df['text'] = df.apply(format_prompt, axis=1)

print(df['text'][0])

"""## **Handling Imbalance**"""

from sklearn.utils import resample

# Undersample majority classes
target_majority = 10000
target_minority = 5000

balanced_dfs = []
for label in df['status'].unique():
    class_df = df[df['status'] == label]
    if len(class_df) > target_majority:
        # Undersample
        class_df = resample(class_df, replace=False, n_samples=target_majority, random_state=42)
    elif len(class_df) < target_minority:
        # Oversample
        class_df = resample(class_df, replace=True, n_samples=target_minority, random_state=42)
    balanced_dfs.append(class_df)

df = pd.concat(balanced_dfs).reset_index(drop=True)
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(f"Balanced dataset size: {df.shape}")
print(df['status'].value_counts())

"""## **Train/Test/Val Split**"""

from sklearn.model_selection import train_test_split

# First split: 80% train, 20% temp
train_df, temp_df = train_test_split(df, test_size=0.2, random_state=42)

# Second split: split temp into 50% validation, 50% test (10% each of total)
val_df, test_df = train_test_split(temp_df, test_size=0.5, random_state=42)

print(f"Train size: {len(train_df)}")
print(f"Validation size: {len(val_df)}")
print(f"Test size: {len(test_df)}")

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df[['text']].reset_index(drop=True))
val_dataset = Dataset.from_pandas(val_df[['text']].reset_index(drop=True))
test_dataset = Dataset.from_pandas(test_df[['text']].reset_index(drop=True))

print(train_dataset)
print(val_dataset)
print(test_dataset)

"""## **Load Tokenizer**"""

model_name = "meta-llama/Llama-3.2-1B-Instruct"

# Load Llama's tokenizer from HuggingFace
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Llama has no padding token by default, so we use the end-of-sequence token as padding
tokenizer.pad_token = tokenizer.eos_token

# Pad on the right side since Llama reads left to right
tokenizer.padding_side = "right"

print("Tokenizer loaded successfully!")
print(f"Vocabulary size: {tokenizer.vocab_size}")

"""# **Baseline Model Evaluation**"""

# Load pure Llama 3.2-1B for baseline evaluation
base_model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    device_map="auto",
)

print("Base model loaded successfully!")

from transformers import pipeline
from sklearn.metrics import accuracy_score, f1_score, classification_report

# testing
test_sample = test_df.reset_index(drop=True)

# Create a text generation pipeline
pipe = pipeline(
    "text-generation",
    model=base_model,
    tokenizer=tokenizer,
    max_new_tokens=10,
    device_map="auto"
)

# Run predictions
true_labels = []
pred_labels = []

labels = ["Normal", "Depression", "Suicidal", "Anxiety", "Bipolar", "Stress", "Personality disorder"]

for i, row in test_sample.iterrows():
    prompt = f"""### Instruction: Classify the mental health status of the following statement.

### Statement: {row['statement']}

### Response:"""

    output = pipe(prompt)[0]['generated_text']
    # Extract only the response part
    response = output.split("### Response:")[-1].strip()

    # Match to closest label
    predicted = "Normal"  # default
    for label in labels:
        if label.lower() in response.lower():
            predicted = label
            break

    true_labels.append(row['status'])
    pred_labels.append(predicted)


    if i % 200 == 0:
        print(f"--- Sample {i} ---")
        print(f"Statement: {row['statement'][:80]}...")
        print(f"True label: {row['status']}")
        print(f"Model response: {response}")
        print(f"Predicted: {predicted}")
        print()

"""## **Baseline Results**"""

print("\n=== Baseline Evaluation Results ===")
print(f"Accuracy: {accuracy_score(true_labels, pred_labels):.4f}")
print(f"F1 Score (weighted): {f1_score(true_labels, pred_labels, average='weighted'):.4f}")
print("\nClassification Report:")
print(classification_report(true_labels, pred_labels))

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix
import numpy as np

# Plot confusion matrix for evaluation
labels_list = ["Normal", "Depression", "Suicidal", "Anxiety", "Bipolar", "Stress", "Personality disorder"]

cm = confusion_matrix(true_labels, pred_labels, labels=labels_list)

plt.figure(figsize=(10, 8))
sns.heatmap(
    cm,
    annot=True,           # Show numbers in each cell
    fmt='d',              # Display as integers
    cmap='Blues',         # Color scheme
    xticklabels=labels_list,
    yticklabels=labels_list
)
plt.title('Confusion Matrix - Baseline Model (Before Fine-tuning)')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('baseline_confusion_matrix.png')  # Save for the report later
plt.show()

print("Confusion matrix saved!")

"""# **QLoRA Finetuning**

## **QLoRA Quantization**
"""

# Configure 4-bit quantization for QLoRA
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Load Llama 3.1-8B with 4-bit quantization
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
)

print("Model loaded successfully!")

"""## **LoRA Adapters**"""

# Prepare model for k-bit (4-bit) training
model = prepare_model_for_kbit_training(model)

# Configure LoRA adapters
lora_config = LoraConfig(
    r=16,                     # Rank of LoRA matrices - higher means more parameters
    lora_alpha=32,            # Scaling factor for LoRA updates
    target_modules=[          # Which layers to apply LoRA to
        "q_proj",             # Query projection
        "v_proj",             # Value projection
        "k_proj",             # Key projection
        "o_proj"              # Output projection
    ],
    lora_dropout=0.05,        # Dropout to prevent overfitting
    bias="none",              # Don't train bias parameters
    task_type="CAUSAL_LM"     # We are doing causal language modeling
)

# Apply LoRA adapters to the model
model = get_peft_model(model, lora_config)

# Show how many parameters are actually trainable
model.print_trainable_parameters()

"""## **QLoRA Training**"""

from trl import SFTConfig, SFTTrainer

training_args = SFTConfig(
    output_dir="./qlora_results",
    num_train_epochs=1,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    fp16=False,
    bf16=False,
    optim="paged_adamw_32bit",
    max_grad_norm=0, # Good choice ✅
    logging_steps=50,
    eval_strategy="steps",
    eval_steps=1010,
    save_strategy="steps",
    save_steps=1010,
    load_best_model_at_end=True,
    report_to="none",
    dataset_text_field="text",
    max_length=160,
)

trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
)

print("Starting QLoRA fine-tuning...")
trainer.train()

"""## **Saving the model just in case!**"""

qlora_save_path = '/kaggle/working/qlora_model'
trainer.save_model(qlora_save_path)
tokenizer.save_pretrained(qlora_save_path)
print("QLoRA model saved!")

"""## **QLoRA Evaluation**"""

from transformers import pipeline
from sklearn.metrics import accuracy_score, f1_score, classification_report
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix


test_sample = test_df.reset_index(drop=True)

# Create pipeline with fine-tuned model
pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=15,
    do_sample=False,
    device_map="auto"
)

true_labels = []
pred_labels = []
labels = ["Normal", "Depression", "Suicidal", "Anxiety", "Bipolar", "Stress", "Personality disorder"]

for i, row in test_sample.iterrows():
    prompt = f"""### Instruction: Classify the mental health status of the following statement.

### Statement: {row['statement']}

### Response:"""

    output = pipe(prompt)[0]['generated_text']
    response = output.split("### Response:")[-1].strip()

    predicted = "Normal"
    for label in labels:
        if label.lower() in response.lower():
            predicted = label
            break

    true_labels.append(row['status'])
    pred_labels.append(predicted)

    if i % 200 == 0:
        print(f"--- Sample {i} ---")
        print(f"Statement: {row['statement'][:80]}...")
        print(f"True label: {row['status']}")
        print(f"Model response: {response}")
        print(f"Predicted: {predicted}")
        print()

"""## **QLoRA Results**"""

qlora_accuracy = accuracy_score(true_labels, pred_labels)
qlora_f1 = f1_score(true_labels, pred_labels, average='weighted')

print("\n=== QLoRA Evaluation Results ===")
print(f"Accuracy: {qlora_accuracy:.4f}")
print(f"F1 Score (weighted): {qlora_f1:.4f}")
print("\nClassification Report:")
print(classification_report(true_labels, pred_labels))

# Confusion matrix
labels_list = ["Normal", "Depression", "Suicidal", "Anxiety", "Bipolar", "Stress", "Personality disorder"]
cm = confusion_matrix(true_labels, pred_labels, labels=labels_list)
plt.figure(figsize=(10, 8))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=labels_list, yticklabels=labels_list)
plt.title('Confusion Matrix - After QLoRA Fine-tuning')
plt.ylabel('True Label')
plt.xlabel('Predicted Label')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('qlora_confusion_matrix.png')
plt.show()

# Save results
qlora_true = true_labels.copy()
qlora_pred = pred_labels.copy()
print("QLoRA results saved!")